language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'figure' ]; then cd .. && eval "mv $currentfolder figure" && cd figure; fi
after_script:
  - npm run coveralls

